// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(appFlavor, 'staging')) {
      return staging;
    }
    if (identical(appFlavor, 'production')) {
      return production;
    }
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfFAzePht8j1YIsnGABUZikm7tTwyvLIU',
    appId: '1:71140175089:web:8b1293315d4d02d7818d50',
    messagingSenderId: '71140175089',
    projectId: 'price-ur-plastic-faab5',
    authDomain: 'price-ur-plastic-faab5.firebaseapp.com',
    databaseURL: 'https://price-ur-plastic-faab5-default-rtdb.firebaseio.com',
    storageBucket: 'price-ur-plastic-faab5.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFAzePht8j1YIsnGABUZikm7tTwyvLIU',
    appId: '1:71140175089:android:6bb69b793b333018818d50',
    messagingSenderId: '71140175089',
    projectId: 'price-ur-plastic-faab5',
    databaseURL: 'https://price-ur-plastic-faab5-default-rtdb.firebaseio.com',
    storageBucket: 'price-ur-plastic-faab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFAzePht8j1YIsnGABUZikm7tTwyvLIU',
    appId: '1:71140175089:ios:9d43ef8b7be0726d818d50',
    messagingSenderId: '71140175089',
    projectId: 'price-ur-plastic-faab5',
    databaseURL: 'https://price-ur-plastic-faab5-default-rtdb.firebaseio.com',
    storageBucket: 'price-ur-plastic-faab5.firebasestorage.app',
    iosBundleId: 'com.example.ecoRecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFAzePht8j1YIsnGABUZikm7tTwyvLIU',
    appId: '1:71140175089:ios:9d43ef8b7be0726d818d50',
    messagingSenderId: '71140175089',
    projectId: 'price-ur-plastic-faab5',
    databaseURL: 'https://price-ur-plastic-faab5-default-rtdb.firebaseio.com',
    storageBucket: 'price-ur-plastic-faab5.firebasestorage.app',
    iosBundleId: 'com.example.ecoRecycle',
  );

  static const FirebaseOptions staging = web;
  static const FirebaseOptions production = web;
}

String? appFlavor;
